### ISSUE TITLE
upload sdists to pypi

### ISSUE THREAD

**Issue by kmike** [ghtdak/qtreactor#13]
Hi,

It seems the sdists are not available at pypi (https://pypi.python.org/pypi/qt4reactor/1.5, https://pypi.python.org/pypi/qt4reactor/1.0). Would you mind uploading them?

**Comment by kmike** [comment]
Adding git tags to releases would be also nice.

**Comment by ghtdak** [comment]
Yeah, I fell down a rabbit hole in figuring pypi out.  Decided to dev branch but now am thinking pypi should be brought up to latest... or close to it.
Releases are also gonna happen.  Its been hood up while I wrestle with trial.

**Comment by ghtdak** [comment]
pypi kinda sucks.  I

**Comment by ghtdak** [comment]
ugh.  Got it.  Tags next.  I'll yank this issue thread.

**Comment by kmike** [comment]
Thanks! 

Why is download_url needed? I think it will work fine without it - all downloads will be from pypi.
