### ISSUE TITLE
provide an easy way to install qt4reactor==1.0

### ISSUE THREAD

**Issue by kmike** [ghtdak/qtreactor#17]
Hi,

`pip install qt4reactor==1.0` doesn't work:

```
pip install --download-cache qt4reactor==1.0 
Downloading/unpacking qt4reactor==1.0
  Could not find a version that satisfies the requirement qt4reactor==1.0 (from versions: 1.5, 1.6)
Cleaning up...
No distributions matching the version for qt4reactor==1.0
```

https://pypi.python.org/pypi/qt4reactor/1.0 incorrectly provides qt4reactor-1.5.tar.gz file.

It seems the only way to install qt4reactor==1.0 is to do that from source checkout like

`pip install -e git+https://github.com/ghtdak/qtreactor.git@0ccabebf54fa268c4110a7442a0c40a0fb57a5e5#egg=qt4reactor`.

It'd be great to have an easier way to do that because `qt4reactor >= 1.5` is backwards incompatible with "old" qt4reactor. Even imports are different - to be compatible with both something like

```
    try:
        from qtreactor import pyqt4reactor as qt4reactor
    except ImportError:
        import qt4reactor
```

is needed. 

It could make sense to call the release 2.0 because of these backwards incompatible changes (100% users must change their code to switch from "old" qt4reactor to "new")

**Comment by ghtdak** [comment]
Ah.  So, I enabled viewing the 1.0 version and now know what happened with my other download.
Seeing if I can fix it

**Comment by kmike** [comment]
`pip install qt4reactor==1.0` works now, thanks!

The tar.gz file contains some unneeded files (pyc, _trial_temp folder), but it doesn't affect anything.

**Comment by ghtdak** [comment]
ugh. thx. fixed :-)

**Comment by kmike** [comment]
:+1:
