### ISSUE TITLE
Reactor does not stop

### ISSUE THREAD

**Issue by RyanHope** [ghtdak/qtreactor#3]
I've tried in my own code and the ircClient test, the reactor does no stop when the window is closed. I am using Qt 4.7.

**Comment by alecu** [comment]
We're having the same issue, running Qt 4.7 + qtreactor both under Linux and Windows.
Sometimes the reactor stops, sometimes it just doesn't.

**Comment by valdur** [comment]
I have a funny version of this issue. If my application actually makes a connection (reactor.connectTCP), it shuts down afterwards nicely. If it doesn't (just starting reactor and making no use of it) - it hangs. 

Right now I have a workaround that makes an dummy connection at startup.

**Comment by ghtdak** [comment]
Works now

Glad I could get to this so quickly :-)

**Comment by ghtdak** [comment]
Ah.  I spoke too quickly although it is fixed now.  The problem was that there was no event fired in the QtReactor by stop.  Now I grab the call and kick the timeout off.
So, now its fixed :-)

**Comment by estan** [comment]
I'm wondering whether this issue may have popped up again? Here's a minimal test case:

``` python
from sys import argv, exit

from PyQt4.QtGui import QDialog, QApplication

import qt4reactor

if __name__ == '__main__':
    app = QApplication(argv)
    app.setQuitOnLastWindowClosed(True)

    qt4reactor.install()

    from twisted.internet import reactor

    dialog = QDialog()
    dialog.show()

    reactor.run()

    exit(0)
```

For me the reactor keeps running even if I close the dialog.

**Comment by estan** [comment]
I have the same problem when running e.g. `ghtTests/trivial_gui_script.py` btw.

**Comment by estan** [comment]
Anyone else seeing this issue again? @ghtdak ?
